# Generated by Django 4.0.6 on 2022-07-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Empresa')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('nit', models.IntegerField(blank=True, null=True, unique=True, verbose_name='NIT')),
                ('phone', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Telefono')),
            ],
        ),
    ]
