# Generated by Django 4.0.6 on 2022-07-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
