# Generated by Django 4.0.6 on 2022-07-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_empresa_id_empresa_empresaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='empresaid',
        ),
        migrations.AddField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
