# Generated by Django 4.0.6 on 2022-07-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_empresa_empresaid_empresa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa'),
        ),
    ]
