# Generated by Django 4.0.6 on 2022-07-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='address',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='name',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='phone',
        ),
    ]
