# Generated by Django 4.0.6 on 2022-07-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_remove_empresa_address_remove_empresa_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nit',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
