# Generated by Django 4.0.6 on 2022-07-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_address_empresa_name_empresa_nit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('nit', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='NIT')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
