# Generated by Django 4.0.6 on 2022-07-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_empresas_delete_empresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
    ]
